name: ski_avalanche_app
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  groovin_widgets: ^2.0.0
  ionicons: ^0.1.2
  speech_to_text: ^4.1.0-nullsafety
  ndialog: ^4.0.1
  circular_check_box: ^1.0.4
  flutter_blue: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true



